disable compilation for Scala 2.13 due to: ``` [error] /git/sstream/src/main/scala/com/evolutiongaming/sstream/Stream.scala:264:31: error during expansion of this match (this is a scalac bug). [error] The underlying error was: type mismatch; [error]  found   : x2.value.type (with underlying type ?B5) [error]  required: B [error]               result   <- cmd match { [error]                               ^ ``